# ------------------------------------------------------------------------------------------------------------------------
# Pipeline to deploy Azure Resources Only
# See readme file for info about the contents of the variable group
# ------------------------------------------------------------------------------------------------------------------------
name: $(date:yyyy).$(date:MM).$(date:dd)$(rev:.r)
pool:
  vmImage: ubuntu-latest

# ------------------------------------------------------------------------------------------------------------------------
trigger:
  # since this repo has both AzDO and GHA pipelines, nothing is run automatically...
  - none
  # batch: true
  # branches:
  #   include:
  #     - main
  # paths:
  #   include:
  #     - '**/*.yml'
  #     - '**/*.yaml'
  #     - '**/*.bicep'

# ----------------------------------------------------------------------------------------------------
parameters:
  - name: deployToEnvironment
    displayName: Deploy To
    type: string
    values:
      - DEV
      - QA
      - PROD
      - DEV-QA-PROD
    default: DEV
  - name: deploymentMode
    displayName: Deploy Mode
    type: string
    values:
      - Incremental
      - Validation
      - Complete
    default: Incremental
  - name: apps
    displayName: Which Apps to build and deploy?
    type: string
    values:
      - API-UI
      - API
      - UI
      - BATCH
      - API-BATCH
      - API-BATCH-UI
    default: 'API-UI'
  - name: parameterFileName
    displayName: 'Bicep Parameter File:'
    type: string
    default: 'main.azdo.bicepparam'
    
  - name: createResourceGroup
    displayName: Create Resource Group?
    type: boolean
    default: true
  - name: publicAccessEnabled
    displayName: Public Access Enabled?
    type: boolean
    default: true
  - name: createDnsZones
    displayName: Create DNS Zones?
    type: boolean
    default: true
  - name: deployAIHub
    displayName: Deploy AI Hub?
    type: boolean
    default: true
  - name: addRoleAssignments
    displayName: Add Role Assignments?
    type: boolean
    default: true
  - name: runMSDevSecOpsScan
    displayName: Run MS DevSecOps Scan?
    type: boolean
    default: false

# ----------------------------------------------------------------------------------------------------
variables:
  - group: AI.Doc.Review.Keys
  - template: vars/var-service-connections.yml

# ----------------------------------------------------------------------------------------------------
stages:
  - ${{ if ne(parameters.deployToEnvironment, 'DEV-QA-PROD') }}:
      - template: pipes/infra-only-pipe.yml
        parameters:
          environments: ['${{ parameters.deployToEnvironment }}']
          templateFolderName: 'infra/bicep'
          templateFileName: 'main.bicep'
          parameterFileName: ${{ parameters.parameterFileName }}
          singleEnvironment: 'true'
          createResourceGroup: ${{ parameters.createResourceGroup }}
          publicAccessEnabled: ${{ parameters.publicAccessEnabled }}
          createDnsZones: ${{ parameters.createDnsZones }}
          deployAIHub: ${{ parameters.deployAIHub }}
          deployBatchApp: ${{ contains(parameters.apps, 'BATCH') }}
          deployUIApp: ${{ contains(parameters.apps, 'UI') }}
          addRoleAssignments: ${{ parameters.addRoleAssignments }}
          runMSDevSecOpsScan: ${{ parameters.runMSDevSecOpsScan }}
          runGHASScan: false

  - ${{ if eq(parameters.deployToEnvironment, 'DEV-QA-PROD') }}:
      - template: pipes/infra-only-pipe.yml
        parameters:
          environments: ['DEV', 'QA', 'PROD']
          templateFolderName: 'infra/bicep'
          templateFileName: 'main.bicep'
          parameterFileName: ${{ parameters.parameterFileName }}
          createResourceGroup: ${{ parameters.createResourceGroup }}
          publicAccessEnabled: ${{ parameters.publicAccessEnabled }}
          createDnsZones: ${{ parameters.createDnsZones }}
          deployAIHub: ${{ parameters.deployAIHub }}
          deployBatchApp: ${{ contains(parameters.apps, 'BATCH') }}
          deployUIApp: ${{ contains(parameters.apps, 'UI') }}
          addRoleAssignments: ${{ parameters.addRoleAssignments }}
          runMSDevSecOpsScan: ${{ parameters.runMSDevSecOpsScan }}
          runGHASScan: false
